name: CI

on:
  push:
    branches:    
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: install sphinx
        run: |
          apt update -y && apt install -y python3-sphinx
          python3 -m pip install pyopengl myst-parser[sphinx] sphinx_rtd_theme
      - name: generate documentation
        run: |
          make html
      - name: commit documentation
        run: |
          cp -r docs/html/* docs/
          touch .nojekyll
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update documentation" -a || true
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: master
#           directory: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
